// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CatFact_GetCatFact_FullMethodName = "/CatFact/GetCatFact"
)

// CatFactClient is the client API for CatFact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatFactClient interface {
	GetCatFact(ctx context.Context, in *CatFactRequest, opts ...grpc.CallOption) (*CatFactResponse, error)
}

type catFactClient struct {
	cc grpc.ClientConnInterface
}

func NewCatFactClient(cc grpc.ClientConnInterface) CatFactClient {
	return &catFactClient{cc}
}

func (c *catFactClient) GetCatFact(ctx context.Context, in *CatFactRequest, opts ...grpc.CallOption) (*CatFactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatFactResponse)
	err := c.cc.Invoke(ctx, CatFact_GetCatFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatFactServer is the server API for CatFact service.
// All implementations must embed UnimplementedCatFactServer
// for forward compatibility
type CatFactServer interface {
	GetCatFact(context.Context, *CatFactRequest) (*CatFactResponse, error)
	mustEmbedUnimplementedCatFactServer()
}

// UnimplementedCatFactServer must be embedded to have forward compatible implementations.
type UnimplementedCatFactServer struct {
}

func (UnimplementedCatFactServer) GetCatFact(context.Context, *CatFactRequest) (*CatFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatFact not implemented")
}
func (UnimplementedCatFactServer) mustEmbedUnimplementedCatFactServer() {}

// UnsafeCatFactServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatFactServer will
// result in compilation errors.
type UnsafeCatFactServer interface {
	mustEmbedUnimplementedCatFactServer()
}

func RegisterCatFactServer(s grpc.ServiceRegistrar, srv CatFactServer) {
	s.RegisterService(&CatFact_ServiceDesc, srv)
}

func _CatFact_GetCatFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatFactServer).GetCatFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatFact_GetCatFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatFactServer).GetCatFact(ctx, req.(*CatFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatFact_ServiceDesc is the grpc.ServiceDesc for CatFact service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatFact_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CatFact",
	HandlerType: (*CatFactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatFact",
			Handler:    _CatFact_GetCatFact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
